version: "3.1"
services:
  sonar: 
    image: "sonarqube:7.1-alpine"
    ports:
      - "9000:9000"
      - "9092:9092"
    network_mode: "host"
    environment:
      SONARQUBE_JDBC_USERNAME: "sonar"
      SONARQUBE_JDBC_PASSWORD: "sonar"
      SONARQUBE_JDBC_URL: "jdbc:postgresql://localhost/sonar"
  db:
    image: "postgres:11.0-alpine"
    ports:
      - "5432:5432"
    network_mode: "host"
    environment:
      POSTGRES_PASSWORD: "sonar"
      POSTGRES_USER: "sonar"
      POSTGRES_DB: "sonar"